### ISSUE TITLE
raise subprocess.CalledProcessError(returncode=process.returncode

### ISSUE THREAD

**Issue by Edward-JianQAQ** [waxnkw/IETrans-SGG.pytorch#23]
Hi,

When I tried to run the demo:
```python
bash cmds/50/transformer/demo_sgdet.sh visualization/demo_imgs/
``` 
I get the result as:
```powershell
=====> ./visualization/demo/custom_data_info.json SAVED !
2023-09-19 03:47:00,240 maskrcnn_benchmark.inference INFO: Start evaluation on 50VG_stanford_filtered_with_attribute_test dataset(3 images).
  0%|                                                                                    | 0/3 [00:00<?, ?it/s]/home/edwardjianqaq/IETrans-SGG.pytorch/maskrcnn_benchmark/structures/boxlist_ops.py:46: UserWarning: This overload of nonzero is deprecated:
        nonzero()
Consider using one of the following signatures instead:
        nonzero(*, bool as_tuple) (Triggered internally at  /opt/conda/conda-bld/pytorch_1607370172916/work/torch/csrc/utils/python_arg_parser.cpp:882.)
  keep = (
100%|████████████████████████████████████████████████████████████████████████████| 3/3 [00:02<00:00,  1.17it/s]
2023-09-19 03:47:02,811 maskrcnn_benchmark.inference INFO: Total run time: 0:00:02.570534 (0.8568445841471354 s / img per device, on 1 devices)
2023-09-19 03:47:02,811 maskrcnn_benchmark.inference INFO: Model inference time: 0:00:02.266249 (0.7554162343343099 s / img per device, on 1 devices)
=====> ./visualization/demo/custom_prediction.pk SAVED !
Traceback (most recent call last):
  File "/home/edwardjianqaq/miniconda3/envs/sgg/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/edwardjianqaq/miniconda3/envs/sgg/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/edwardjianqaq/miniconda3/envs/sgg/lib/python3.8/site-packages/torch/distributed/launch.py", line 260, in <module>
    main()
  File "/home/edwardjianqaq/miniconda3/envs/sgg/lib/python3.8/site-packages/torch/distributed/launch.py", line 255, in main
    raise subprocess.CalledProcessError(returncode=process.returncode,
subprocess,
subprocess.CalledProcessError: Command '['/home/edwardjianqaq/miniconda3/envs/sgg/bin/python', '-u', 'tools/demo.py', '--local_rank=0', '--config-file', 'configs/sup-50.yaml', 'MODEL.ROI_RELATION_HEAD.USE_GT_BOX', 'False', 'MODEL.ROI_RELATION_HEAD.USE_GT_OBJECT_LABEL', 'False', 'MODEL.ROI_RELATION_HEAD.PREDICTOR', 'TransformerPredictor', 'SOLVER.PRE_VAL', 'False', 'MODEL.ROI_RELATION_HEAD.PREDICT_USE_BIAS', 'True', 'SOLVER.IMS_PER_BATCH', '8', 'TEST.IMS_PER_BATCH', '1', 'DTYPE', 'float16', 'SOLVER.MAX_ITER', '40000', 'SOLVER.VAL_PERIOD', '2000', 'SOLVER.CHECKPOINT_PERIOD', '2000', 'GLOVE_DIR', '/home/edwardjianqaq/exps/glove', 'MODEL.PRETRAINED_DETECTOR_CKPT', './maskrcnn_benchmark/pretrained/pretrained_faster_rcnn/model_final.pth', 'OUTPUT_DIR', './visualization/demo', 'TEST.METRIC', 'R', 'TEST.CUSTUM_EVAL', 'True', 'TEST.CUSTUM_PATH', 'visualization/demo_imgs/', 'DETECTED_SGG_DIR', './visualization/demo']' died with <Signals.SIGSEGV: 11>.
``` 

May ask if the running is successful? How can I solve the error here?(I tried to search for an answer but failed)

Your help will be greatly appreciated as it is very important to me!!!

**Comment by Edward-JianQAQ** [comment]
Oh I found just rebuild the package will work.
